openapi: 3.0.0
info:
  title: Leads Ingestion API
  version: 1.0.0
  description: API for ingesting leads from WordPress Contact Form 7 submissions.
paths:
  /api/leads:
    post:
      summary: Submit a new lead
      operationId: storeLead
      tags:
        - Leads
      parameters:
        - in: header
          name: X-API-Key
          schema:
            type: string
          required: true
          description: API Key of the submitting site.
      requestBody:
        required: true
        description: Lead data payload (Max 1MB).
        content:
          application/json:
            schema:
              type: object
              required:
                - form_name
                - form_data
              properties:
                form_name:
                  type: string
                  description: Name or ID of the form.
                  example: "Contact Form 7"
                form_data:
                  type: object
                  description: JSON object containing all form fields.
                  example:
                    your-name: "John Doe"
                    your-email: "john@example.com"
                    your-message: "Hello!"
                submitted_at:
                  type: string
                  format: date-time
                  description: Optional original submission timestamp.
      responses:
        '201':
          description: Lead created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  lead_id:
                    type: integer
                    example: 42
        '401':
          description: Unauthorized - Invalid or missing API Key
        '413':
          description: Payload Too Large - Request body exceeds 1MB
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "The form name field is required."
                  errors:
                    type: object
        '429':
          description: Too Many Requests (Rate Limit Exceeded)